filebeat.inputs:
  - type: container
    enabled: true
    paths:
      - '/var/lib/docker/containers/*/*.log'
    processors:
      - add_docker_metadata:
          host: "unix:///var/run/docker.sock"
          match_fields: ["container.id"]
          match_pids: ["process.pid", "process.parent.pid"]
      - decode_json_fields:
          fields: ["message"]
          target: ""
          overwrite_keys: true
          add_error_key: true
      - drop_fields:
          fields: ["agent", "ecs", "input"]

processors:
  - add_host_metadata:
      when.not.contains.tags: forwarded
  - add_fields:
      target: 'fields'
      fields:
        environment: homelab
        stack: elk
        log_type: docker

# Send to Logstash instead of Elasticsearch
output.logstash:
  hosts: ["logstash:5044"]

setup.template.enabled: false

logging.level: info
logging.to_stderr: true
