node.name: logstash-homelab
path.data: /usr/share/logstash/data
path.config: /usr/share/logstash/pipeline
path.logs: /usr/share/logstash/data/logs
pipeline.workers: 2
pipeline.batch.size: 125
pipeline.batch.delay: 50
xpack.monitoring.enabled: false
log.level: info
log.format: json
